import Contact from "./Contact";

export const metadata = {
  title: "Contact || Next Gadgets",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return <Contact></Contact>;
};

export default ContactPage;
