import Terms from "./Terms";

export const metadata = {
  title: "Terms & Conditions || Next Gadgets",
  description: "Generated by create next app",
};

const TermsPage = () => {
  return <Terms></Terms>;
};

export default TermsPage;
