import About from "./About";

export const metadata = {
  title: "About Us || Next Gadgets",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return <About></About>;
};

export default AboutPage;
