import Profile from "./Profile";

export const metadata = {
  title: "Profile || Next Gadgets",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return <Profile></Profile>;
};

export default ProfilePage;
