import FAQ from "./FAQ";

export const metadata = {
  title: "FAQ & Help || Next Gadgets",
  description: "Generated by create next app",
};

const FAQPage = () => {
  return <FAQ></FAQ>;
};

export default FAQPage;
