import Career from "./Career";

export const metadata = {
  title: "Career || Next Gadgets",
  description: "Generated by create next app",
};

const CareerPage = () => {
  return <Career></Career>;
};

export default CareerPage;
